In [2]:
import numpy as np

In [6]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,2,2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# vertically stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# horizontal stack 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])